version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04

formats:
    - epub

python:
  version: 3.8
  install:
    - requirements: requirements/docs.txt
    - requirements: requirements/readthedocs.txt
